# Generated by Django 3.0.6 on 2020-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('product_group', models.CharField(choices=[(1, 'Phone'), (2, 'Cucumber'), (3, 'Toothbrush')], default=1, max_length=10)),
                ('stock_balance', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
