# Generated by Django 3.0.6 on 2020-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200513_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_group',
            field=models.CharField(choices=[('1', 'Phone'), ('2', 'Cucumber'), ('3', 'Toothbrush')], default='1', max_length=10),
        ),
    ]
