# Generated by Django 3.0.6 on 2020-05-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_is_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_not_sold',
            field=models.BooleanField(default=True),
        ),
    ]
